on: push 
jobs: 
  testing-action:
    runs-on: ubuntu-latest
    permissions: write-all
    steps: 
      - uses: actions/checkout@v2
      - uses: ./.github/actions/issue
        id: issue
        with: 
          token: ${{ secrets.GITHUB_TOKEN }}
          title: Title
          body: Body
          assignees: |
            miguelampudia
            appgate-miguel-ampudia
      - run: |
          echo ${{ steps.issue.outputs.issue }}
      - uses: ./.github/actions/hello
        id: hello
        with:
          who-to-greet: "World"
      - uses: ./.github/actions/hello-docker
        id: hello-docker
        with:
          who-to-greet: "World"
      - run: |
          echo "Time: ${{ steps.hello.outputs.time }}"
          echo "Time: ${{ steps.hello-docker.outputs.time }}"
          echo $HELLO